version: '3.8'
services:
  app:
    container_name: nodejs-app
    build: .
    ports:
      - "5005:5005"
    env_file: 
      - ./.env
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
